### ISSUE TITLE
Визначення кольору за балами

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-23-Promises-Fetch#1]
https://github.com/BohdanLuts/home-work-lesson-23-Promises-Fetch/blob/1ceb01cd93ff9778bc2c3fb4b01d6c2f7b7e088a/js/index.js#L97
- для встановлення залежності по прямій залежності зручно використосувати об'єкти (або мапи):
```
const beauforScaleColor = {
    0: '#fff',
    1: '#aef1f9',
    2: '#96f7dc',
    3: '#96f7b4',
    4: '#6ff46f',
   ...
  };
```

- краще явно вказати колір для штилю, оскільки якщо макет передбачатиме не біле тло сторінки, то штиль буде позначено кольором тла батьківського елементу.

**Comment by BohdanLuts** [comment]
Замінив на простіше рішення.
Дійсно, виявилося зручніше.

**Comment by BohdanLuts** [comment]
Переробив з функції на звичайний об'єкт. Сенсу лишати функцію для кольору не було (заглянув у наступний іншюз, де був приклад використання), тому в новому коміті виправив.
