### ISSUE TITLE
Дублювання коду

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-23-Promises-Fetch#2]
https://github.com/BohdanLuts/home-work-lesson-23-Promises-Fetch/blob/1ceb01cd93ff9778bc2c3fb4b01d6c2f7b7e088a/js/index.js#L127
- для уникнення дублювання можна використати силу селекторів і прогнати по всих елементах обходом по колекції:
```
  const beauforScaleDays = document.querySelectorAll('tr>td:nth-child(4)');

  beauforScaleDays.forEach((bsd, i) => {
    const beauforScaleDayEl = document.createElement('p');
    bsd.append(beauforScaleDayEl);
    beauforScaleDayEl.textContent = calcBeauforScale(
      weather.daily.windspeed_10m_max[i]
    );
    bsd.setAttribute(
      'style',
      `background: ${
        beauforScaleColor[calcBeauforScale(weather.daily.windspeed_10m_max[i])]
      }`
    );
  });
```

- аналогічно і для інших стовпчиків

**Comment by pecourses** [comment]
- ще надійніше буде не прив'язуватися в селекторі до структури таблиці, раптом додамо ще стовпці, і навішувати на всі комірки одного стовпця однаковий клас, тоді можна отримувати колекцію по класу.

**Comment by BohdanLuts** [comment]
Використав Ваші рекомендації - дійсно ефективна річ. В наступних коммітах зроблю для інших стовпців.

**Comment by BohdanLuts** [comment]
Виконано для інших стовпчиків таблиці.
